/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_bme_mit_opencbdc_OpenCBDCJavaClient */

#ifndef _Included_hu_bme_mit_opencbdc_OpenCBDCJavaClient
#define _Included_hu_bme_mit_opencbdc_OpenCBDCJavaClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_bme_mit_opencbdc_OpenCBDCJavaClient
 * Method:    send
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_send
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     hu_bme_mit_opencbdc_OpenCBDCJavaClient
 * Method:    mint
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_mint
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     hu_bme_mit_opencbdc_OpenCBDCJavaClient
 * Method:    fan
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_fan
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     hu_bme_mit_opencbdc_OpenCBDCJavaClient
 * Method:    sync
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_sync
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     hu_bme_mit_opencbdc_OpenCBDCJavaClient
 * Method:    newAddress
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_newAddress
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     hu_bme_mit_opencbdc_OpenCBDCJavaClient
 * Method:    info
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_info
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     hu_bme_mit_opencbdc_OpenCBDCJavaClient
 * Method:    importInput
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_importInput
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     hu_bme_mit_opencbdc_OpenCBDCJavaClient
 * Method:    confirmTx
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_confirmTx
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
