Organizations:
- &OrdererOrg
    Name: example.com
    ID: OrdererMSP
    MSPDir: ./../crypto-config/ordererOrganizations/example.com/msp
    AdminPrincipal: Role.ADMIN

- &Org1
    Name: CentralBankOrg
    ID: CentralBankOrgMSP
    MSPDir: ./../crypto-config/peerOrganizations/centralbank.example.com/msp
    AdminPrincipal: Role.ADMIN
    AnchorPeers:
    - Host: peer0.centralbank.example.com
      Port: 7051

- &Org2
    Name: FIOrg
    ID: FIOrgMSP
    MSPDir: ./../crypto-config/peerOrganizations/fi.example.com/msp
    AdminPrincipal: Role.ADMIN
    AnchorPeers:
    - Host: peer0.fi.example.com
      Port: 7051

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
    - orderer0.example.com:7050

    BatchTimeout: 250ms
    BatchSize:
        MaxMessageCount: 50
        AbsoluteMaxBytes: 100 MB
        PreferredMaxBytes: 1 MB

    MaxChannels: 0

    Organizations:

Application: &ApplicationDefaults
    Organizations:

Profiles:
    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
            - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Org1
                - *Org2
    ChannelConfig:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - *Org1
            - *Org2